FORMAT: 1A

# MockAPI
A mock up to see what calls are needed by the frontend code

# Group User
User related resources of the **API**

## Login [/login]
### Authenticate user [POST] 

+ Request (application/json)

        { 
            "login": "foo@example.com",
            "password": "abc123"
        }

+ Response 200 (application/json)

        { 
            "_links" : {
                "self": { "href": "/users/123" }
            },
            "id": "123" 
        }

+ Response 403 (application/json)

        { "message": "the credentials supplied are invalid" }

## Forgot password [/login/forgot]
### Forgot password [POST] 

+ Request (application/json)

        { 
            "login": "foo@example.com"
        }

+ Response 200 (application/json)

        { 
            "success": true,
            "message": "reset instructions have been sent"
        }

+ Response 401 (application/json)

        { 
            "success": false,
            "message": "the email address is not found" 
        }

## Reset password [/login/reset]
### Reset password [POST] 

+ Request (application/json)

        { 
            "userID": "123"
            "token": "xM4BzcKGgzq0LQAyPSPD"
            "newPassword": "MyNewCoolSecurePassword"
        }

+ Response 200 (application/json)

        { 
            "success": true,
            "message": "the password has been updated"
        }

+ Response 401 (application/json)

        { 
            "success": false,
            "message": "the password does not meet the complexity requirements" 
        }


## User [/user/{id}]
+ Model
    
    HAL+JSON representation

    + Body
    
            {
                "_links" : { "self": { "href": "/user/123" } },
                "id" : "123",
                "email" : "foo@example.com",
                "firstName" : "Danny",
                "lastName" : "Tanner",
                "phone" : "4055551212",
                "address1" : "1882 Gerard St.",
                "state" : "CA",
                "zip" : "94134"
            }


### Get User [GET] 
+ Parameters
    + id (int, required, '123')
    
+ Response 200 (application/json)

    [User][]
    
+ Response 401

+ Response 403


### Update User [PUT] 
+ Parameters
    + id (int, required, '123')

+ Request (application/json)

        {
            "email" : "foo@example.com",
            "firstName" : "Danny",
            "lastName" : "Tanner",
            "phone" : "4055551212",
            "address1" : "1882 Gerard St.",
            "state" : "CA",
            "zip" : "94134"
        }
    
+ Response 200 (application/json)

    [User][]
    
+ Response 401

+ Response 403


## Project Collection [/project]

### List projects [GET]

+ Response 200 (application/json)

        [{
            "_links" : { "self": { "href": "/project/1" } },
            "id" : "1",
            "name" : "Project Name #1",
            "startDate" : "2015-02-14",
            "finishDate" : "TBD",
            "documents" : 1000,
            "workers" : 10,
            "completionPercentage" : 46
        },
        {
            "_links" : { "self": { "href": "/project/2" } },
            "id" : "2",
            "name" : "Project Name #2",
            "startDate" : "2015-04-01",
            "finishDate" : "TBD",
            "documents" : 2000,
            "workers" : 4,
            "completionPercentage" : 33
        },
        {
            "_links" : { "self": { "href": "/project/3" } },
            "id" : "3",
            "name" : "Project Name #3",
            "startDate" : "2015-07-04",
            "finishDate" : "TBD",
            "documents" : 3000,
            "workers" : 10,
            "completionPercentage" : 12
        }]


## Project [/project/{id}]

+ Model
    
    + Body
    
            {
                "_links" : { "self": { "href": "/project/1" } },
                "id" : "1",
                "details" : "These are some project details to be displayed in the project description box",
                "startDate" : "2015-01-01",
                "workers" : "10",
                "statistics" : {
                    "splits" : { complete: 10, total: 100 },
                    "indexes" : { complete: 5, total: 32 },
                    "validations" : { complete: 73, total: 100 },
                    "dc" : { complete: 5, total: 10 },
                    "percentage" : 80,
                }
            }

### Get project [GET] 
+ Parameters
    + id (int, required, '1')
    
+ Response 200 (application/json)

    [Project][]
    
+ Response 401

+ Response 403

## Project contacts [/project/{id}/contacts{?pending}]
+ Parameters
    + id (int, required) ... project ID
    + pending (optional) ... including only pending contacts

### List project contacts [GET]

+ Response 200 (application/json)

        [{
            "_links" : { "self": { "href": "/user/123" } },
            "id" : "123",
            "email" : "foo@example.com",
            "firstName" : "Danny",
            "lastName" : "Tanner",
            "phone" : "4055551212",
            "address1" : "1882 Gerard St.",
            "state" : "CA",
            "zip" : "94134",
            "lastLogin" : "2014-12-31T14:43"
        },
        {
            "_links" : { "self": { "href": "/user/456" } },
            "id" : "456",
            "email" : "dj@example.com",
            "firstName" : "D.J.",
            "lastName" : "Tanner",
            "phone" : "4055551212",
            "address1" : "1882 Gerard St.",
            "state" : "CA",
            "zip" : "94134",
            "lastLogin" : "2014-12-31T14:43"
        },
        {
            "_links" : { "self": { "href": "/user/789" } },
            "id" : "789",
            "email" : "kgibbler@example.com",
            "firstName" : "Kimmy",
            "lastName" : "Gibbler",
            "phone" : "4055551212",
            "address1" : "1882 Gerard St.",
            "state" : "CA",
            "zip" : "94134",
            "isPending" : true,
            "invitationSent" : "2014-12-31T15:31"
        }]

### Invite contacts to project [POST]

+ Request (application/json)

        { 
            "existing": [
                "123",
                "456"
            ],
            "new": [
                "foo@example.com",
                "bar@example.com"
            ]
        }

+ Response 200 (application/json)

    [User][]




